title:
  text: "Craft"
books:
  - "Cover Craft"
  # - "First Degree"
  # - "Second Degree"
  # - "Third Degree"
  # - "Call off - Call on"
  # - "Installation"
  # - "Appendix"
colour:
  enabled: false
  italic: true
  roles: true
  highlight_roles: true
text:
  default:
    height: 23
    cursor:
      family: Merriweather
      style: ""
      size: 18
      colour: [0, 0, 0]
      fill: [255, 255, 255]
  bold:
    height: 23
    cursor:
      family: Merriweather
      style: "B"
      size: 18
      colour: null
      fill: null
  italic:
    height: 23
    cursor:
      family: Merriweather Light
      style: "I"
      size: 18
      colour: [215, 0, 0]
      fill: [255, 255, 255]
  heading:
    height: 23
    cursor:
      family: Montserrat Light
      style: ""
      size: 18
      colour: [0, 0, 0]
      fill: [255, 255, 255]
  heading_spacing:
    height: 9
  template:
    height: 13.5
    cursor:
      family: Montserrat Light
      style: ""
      size: 13
      colour: [0, 0, 0]
      fill: [255, 255, 255]
roles:
  W. M.:
    dark: [255, 255, 255]
    light: [255, 255, 255]
  S. W.:
    dark: [108, 158, 235]
    light: [164, 194, 244]
  J. W.:
    dark: [147, 196, 125]
    light: [182, 215, 168]
  S. D.:
    dark: [246, 178, 107]
    light: [249, 203, 156]
  J. D.:
    dark: [142, 124, 195]
    light: [180, 167, 214]
  I. G.:
    dark: [118, 165, 175]
    light: [162, 192, 201]
  Can.:
    dark: [255, 217, 102]
    light: [255, 229, 153]
  I. M.:
    dark: [0, 204, 153]
    light: [153, 255, 214]
  A. D. C.:
    dark: [0, 230, 230]
    light: [128, 255, 255]
  D. C.:
    dark: [0, 230, 230]
    light: [128, 255, 255]
  M.-E.:
    dark: [255, 128, 179]
    light: [255, 179, 209]
page:
  top_margin: 28.4
  margin_size: 38.4
  bottom_margin: 38.4
